config/routes.rb
LearnRails::Application.routes.draw do
  resources :contacts, only: [:new, :create]
	root to: 'visitors#new'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_no_table

	column :name,    :string
	column :email,   :string
	column :content, :string

	validates_presence_of :name
	validates_presence_of :email
	validates_presence_of :content
	REGEX_EMAIL = /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
	validates_format_of   :email, with: REGEX_EMAIL
	validates_length_of   :content, maximum: 500

	def update_spreadsheet
		connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])
		ss = connection.spreadsheet_by_title('Learn-Rails-Example')
		if ss.nil?
			ss = connection.create_spreadsheet('Learn-Rails-Example')
		end
		ws = ss.worksheets[0]
		last_row = 1 + ws.num_rows
		ws[last_row, 1] = Time.new
		ws[last_row, 2] = self.name
		ws[last_row, 3] = self.email
		ws[last_row, 4] = self.content
		ws.save
	end
end

app/models/owner.rb
class Owner

	def name
		name = 'Foobar Kadigan'
	end
	def birthdate
		birthdate = Date.new(1990, 12, 22)
	end
	def countdown
		today = Date.today
		birthday = Date.new(today.year, birthdate.month, birthdate.day)
		if birthday > today
			countdown = (birthday - today).to_i
		else
			countdown = (birthday.next_year - today).to_i
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end
	def create
		@contact = Contact.new(secure_params)
		if @contact.valid?
			@contact.update_spreadsheet
			UserMailer.contact_email(@contact).deliver
			flash[:notice] = "Message sent from #{@contact.name}."
			redirect_to root_path
		else
			render :new
		end
	end
	
	private
	def secure_params
		params.require(:contact).permit(:name, :email, :content)
	end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def new
		@owner = Owner.new
		flash[:notice] = "Welcome!"
		flash[:alert]  = "My birthday is soon."
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contacts<% end %>
<h3>Contact</h3>
<div class="form">
	<%= simple_form_for @contact do |form| %>
		<%= form.error_notification %>
		<%= form.input :name, autofocus: true %>
		<%= form.input :email %>
		<%= form.input :content, as: :text %>
		<%= form.button :submit, 'Submit', class: 'submit' %>
	<% end %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
		<%= content_tag :div, msg, :class => "flash_#{name}" %>
	<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
<li><%= link_to 'Home', root_path %></li>
<%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<% # add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
<meta name="description" content="<%= content_for?(:description) ?
yield(:description) : "Learn Rails" %>">
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
%>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body>
<header>
<%= render 'layouts/navigation' %>
</header>
<main role="main">
<%= render 'layouts/messages' %>
<%= yield %>
</main>
</body>

app/views/visitors/new.html.erb
<h3>Home</h3>
<p>Welcome to the home of <%= @owner.name %>.</p>
<p>I was born on <%= @owner.birthdate %>.</p>
<p>Only <%= @owner.countdown %> days until my birthday!</p>